version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      #- "8080:80"
      #- "8000:80"
      - "80:80"
      #- "8000:8000"
      #- "80:80"

    volumes:
      ##- ./:/src
      - /home/mss87/classmo:/src
      ##- ./config/nginx:/etc/nginx/conf.d
      - /home/mss87/classmo/config/nginx:/etc/nginx/conf.d
      # commented this- /home/mss87/classmo/config/nginx:/etc/nginx
    depends_on:
      - web
  db:
    image: postgres:9.6
    ##build:
    ##  context: ./
    ##  dockerfile: Dockerfile_postgres
    expose:
      - 5432
    volumes:
      ##- ./:.
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    #environment:
      #- POSTGRES_USER:classmouser
      #- POSTGRES_PASSWORD:classmopassword
  web:
    image: sidhumehtab/classmo_web
    build: .
    #ports:
    #  - "8000:8000"
    depends_on:
      - db
    expose:
      #- "8080"
      - "80"
      #- "8000"
      #- "80"

volumes:
  pg_data: {}
  pg_backups: {}
