version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres:9.6
    ##build:
    ##  context: ./
    ##  dockerfile: Dockerfile_postgres
    expose:
      - 5432
    volumes:
      ##- ./:.
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    #environment:
      #- POSTGRES_USER:classmouser
      #- POSTGRES_PASSWORD:classmopassword
  web:
    build: .
    ##ports:
      ##- "8000:8000"
    depends_on:
      - db
    expose:
      - "8000"

volumes:
  pg_data: {}
  pg_backups: {}
