# Generated by Django 2.0.1 on 2018-02-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='adjusted_score',
            field=models.FloatField(default=1.0),
        ),
    ]
