# Generated by Django 2.0.1 on 2018-03-03 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 3, 18, 18, 14, 640371, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='topic_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_post', to='discussions.Post'),
        ),
    ]
