# Generated by Django 2.0.1 on 2018-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180217_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
