# Generated by Django 2.0.2 on 2018-02-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Session'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
