# Generated by Django 2.0.1 on 2018-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180304_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='New York', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='NY', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='00000', max_length=128),
        ),
    ]
