# Generated by Django 2.0.2 on 2018-02-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20180221_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
    ]
