# Generated by Django 2.0.1 on 2018-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='all_courses_body',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='company',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='discussion_body',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='jumbotron_color',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='my_courses_body',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='secondary_color',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='secondary_text_color',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='splash_license_1',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='splash_license_2',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='splash_license_3',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='splash_url_1',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='splash_url_2',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='splash_url_3',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='welcome_body',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='config',
            name='welcome_title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
