# Generated by Django 2.0.2 on 2018-02-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_assignment_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='Homework',
        ),
    ]
