# Generated by Django 2.0.1 on 2018-02-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('schedules', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
