# Generated by Django 2.0.2 on 2018-02-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_profile'),
        ('schedules', '0005_auto_20180223_0116'),
    ]

    operations = [
    ]
