# Generated by Django 2.0.1 on 2018-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20180414_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='jumbotron_color',
            field=models.CharField(blank=True, default='#eceeef', max_length=7),
        ),
        migrations.AlterField(
            model_name='config',
            name='primary_color',
            field=models.CharField(blank=True, default='#417690', max_length=7),
        ),
        migrations.AlterField(
            model_name='config',
            name='primary_text_color',
            field=models.CharField(blank=True, default='#f5dd5d', max_length=7),
        ),
        migrations.AlterField(
            model_name='config',
            name='secondary_color',
            field=models.CharField(blank=True, default='#79aec8', max_length=7),
        ),
        migrations.AlterField(
            model_name='config',
            name='secondary_text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7),
        ),
    ]
