# Generated by Django 2.0.1 on 2018-04-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180414_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='all_courses_body',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='company',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='discussion_body',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='font_family',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='my_courses_body',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='welcome_body',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
        migrations.AlterField(
            model_name='config',
            name='welcome_title',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
    ]
