# Generated by Django 2.0.2 on 2018-04-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20180414_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='small_logo',
            field=models.CharField(blank=True, default='', max_length=1280),
        ),
    ]
