# Generated by Django 2.0.1 on 2018-04-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20180428_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='created_date',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='config',
            name='modified_date',
        ),
    ]
