# Generated by Django 2.0.1 on 2018-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_auto_20180429_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
